import { AfterViewInit, Component, ElementRef, HostListener, OnDestroy, ViewChild, effect, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { EditorService } from './editor.service';
import { TOOLS } from './tools';
import { translate } from './i18n';
import { BLENDS, Layer, newLayer } from '../../../../packages/domain/src/document';
interface Release {version:string;date:string;summary:string;markdown:string;breakingChanges:string[];}
@Component({selector:'xds-root',standalone:true,imports:[FormsModule],templateUrl:'./app.component.html'})
export class AppComponent implements AfterViewInit,OnDestroy {
  @ViewChild('canvas')canvas?:ElementRef<HTMLCanvasElement>;@ViewChild('viewport')viewport?:ElementRef<HTMLDivElement>;@ViewChild('spatialHost')spatialHost?:ElementRef<HTMLDivElement>;
  readonly tools=TOOLS;readonly blends=BLENDS;readonly theme=signal(localStorage.getItem('xds-theme')??'dark');readonly locale=signal(localStorage.getItem('xds-locale')??'en');readonly panels=signal(true);readonly workspace=signal('Drawing');readonly about=signal(false);readonly spatial=signal(false);readonly dialog=signal(false);readonly projects=signal<{id:string;name:string;updatedAt:string}[]>([]);readonly apiToken=signal('');readonly releases=signal<Release[]>([]);readonly currentVersion=signal('…');readonly chosenVersion=signal('');readonly noteGroups=signal<{title:string;items:string[]}[]>([]);readonly aboutError=signal('');readonly panelOrder=signal(['properties','layers']);private frame=0;private pan?:{x:number;y:number;left:number;top:number};private disposeSpatial?:()=>void;
  constructor(readonly editor:EditorService){effect(()=>{editor.document();editor.selectedId();editor.revision();this.schedule();});effect(()=>{window.document.documentElement.dataset['theme']=this.theme();localStorage.setItem('xds-theme',this.theme());});effect(()=>{window.document.documentElement.lang=this.locale();localStorage.setItem('xds-locale',this.locale());});}
  clampSize(value:number){return Number.isFinite(value)?Math.max(1,Math.min(200,value)):4;}
  t(key:string){return translate(key,this.locale());}
  ngAfterViewInit(){this.fit();this.schedule();void this.loadReleaseIndex();if(location.pathname==='/about')this.about.set(true);}
  ngOnDestroy(){cancelAnimationFrame(this.frame);this.disposeSpatial?.();}
  schedule(){cancelAnimationFrame(this.frame);this.frame=requestAnimationFrame(()=>{if(this.canvas)this.editor.renderer.draw(this.canvas.nativeElement,this.editor.document(),this.editor.selectedId(),()=>this.schedule(),this.editor.painting);});}
  private point(event:PointerEvent){const rect=this.canvas!.nativeElement.getBoundingClientRect();return{x:(event.clientX-rect.left)*this.editor.document().width/rect.width,y:(event.clientY-rect.top)*this.editor.document().height/rect.height};}
  pointerDown(event:PointerEvent){if(event.button!==0)return;event.preventDefault();this.canvas!.nativeElement.setPointerCapture(event.pointerId);if(this.editor.tool()==='hand'){const view=this.viewport!.nativeElement;this.pan={x:event.clientX,y:event.clientY,left:view.scrollLeft,top:view.scrollTop};}else this.editor.start(this.point(event));}
  pointerMove(event:PointerEvent){if(this.pan){const view=this.viewport!.nativeElement;view.scrollLeft=this.pan.left-event.clientX+this.pan.x;view.scrollTop=this.pan.top-event.clientY+this.pan.y;}else this.editor.move(this.point(event));}
  pointerUp(){this.pan=undefined;this.editor.end();}
  pointerCancel(){this.pan=undefined;this.editor.cancel();}
  fit(){const view=this.viewport?.nativeElement;if(view)this.editor.zoom.set(Math.max(.1,Math.min(1,(view.clientWidth-100)/this.editor.document().width,(view.clientHeight-100)/this.editor.document().height)));}
  setZoom(value:number){this.editor.zoom.set(Math.min(3,Math.max(.1,value)));}
  number(event:Event){return Number((event.target as HTMLInputElement).value);}
  text(event:Event){return(event.target as HTMLInputElement).value;}
  patchNumber(key:'x'|'y'|'width'|'height'|'rotation'|'opacity'|'fontSize'|'strokeWidth',event:Event){let value=this.number(event);if(!Number.isFinite(value))return;const limits:Record<string,[number,number]>={x:[-100000,100000],y:[-100000,100000],width:[1,16384],height:[1,16384],rotation:[-360,360],opacity:[0,1],fontSize:[1,500],strokeWidth:[0,200]};value=Math.min(limits[key][1],Math.max(limits[key][0],value));this.editor.updateLayer({[key]:value});}
  adjustment(key:'brightness'|'contrast'|'saturation'|'blur',event:Event){const layer=this.editor.selected();if(layer)this.editor.updateLayer({adjustments:{...layer.adjustments,[key]:this.number(event)}});}
  resetAdjustments(){this.editor.updateLayer({adjustments:{brightness:100,contrast:100,saturation:100,blur:0}});}
  async imageInput(event:Event){const input=event.target as HTMLInputElement;try{if(input.files?.[0])await this.editor.importImage(input.files[0]);}catch(error){this.notify(error);}input.value='';}
  async projectInput(event:Event){const input=event.target as HTMLInputElement;try{const file=input.files?.[0];if(file){if(file.size>35_000_000)throw new Error('Project exceeds 35 MB.');this.editor.open(await file.text());this.fit();}}catch(error){this.notify(error);}input.value='';}
  newDocument(){if(this.editor.document().layers.length&&!confirm('Create a new document? Save your current project first.'))return;this.editor.reset();this.fit();}
  sample(){this.editor.reset();const a=newLayer('ellipse',crypto.randomUUID(),{x:160,y:180},'#0d59f2','#0d59f2',0);a.width=420;a.height=420;const b=newLayer('rectangle',crypto.randomUUID(),{x:500,y:290},'#9bffc9','#9bffc9',0);b.width=350;b.height=300;b.rotation=-12;const c=newLayer('text',crypto.randomUUID(),{x:130,y:65},'#17202f','#17202f',0);c.text='Make something yours.';c.fontSize=64;c.width=950;c.height=80;this.editor.document.update(d=>({...d,name:'First exploration',background:'#f4f3ed',layers:[a,b,c]}));this.editor.selectedId.set(b.id);this.editor.status.set('Sample ready. Every element is editable.');}
  dropPanel(event:DragEvent,target:string){event.preventDefault();const id=event.dataTransfer?.getData('text/x-xds-panel');if(!id||!this.panelOrder().includes(id))return;const list=this.panelOrder().filter(x=>x!==id);list.splice(list.indexOf(target),0,id);this.panelOrder.set(list);}
  dragPanel(event:DragEvent,id:string){event.dataTransfer?.setData('text/x-xds-panel',id);}
  notify(error:unknown){this.editor.status.set(error instanceof Error?error.message:'The operation could not be completed.');}
  @HostListener('document:click',['$event']) closeMenus(event:MouseEvent){const target=event.target as HTMLElement;if(!target.closest('.menus summary'))for(const detail of window.document.querySelectorAll<HTMLDetailsElement>('.menus details[open]'))detail.open=false;}
  @HostListener('window:keydown',['$event']) key(event:KeyboardEvent){if(['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement).tagName)||this.about()||this.dialog())return;const modifier=event.ctrlKey||event.metaKey;if(modifier&&event.key.toLowerCase()==='s'){event.preventDefault();this.editor.save();return;}if(modifier&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?this.editor.redo():this.editor.undo();return;}if(modifier&&event.key.toLowerCase()==='d'){event.preventDefault();this.editor.duplicate();return;}if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();this.editor.remove();}if(event.key==='Escape')this.editor.cancel();const tool=this.tools.find(t=>t.shortcut===event.key.toUpperCase());if(tool&&!modifier)this.editor.tool.set(tool.id);}
  async loadReleaseIndex(){try{const response=await fetch('/assets/changelog/index.json');if(!response.ok)throw new Error('Release notes unavailable');const data=await response.json();this.releases.set(data.entries);this.currentVersion.set(data.currentVersion);await this.selectVersion(new URLSearchParams(location.search).get('version')??data.currentVersion,false);}catch(error){this.aboutError.set(error instanceof Error?error.message:'Release notes unavailable');}}
  async selectVersion(version:string,updateUrl=true){this.chosenVersion.set(version);const entry=this.releases().find(r=>r.version===version);this.noteGroups.set([]);if(!entry){this.aboutError.set('Unknown version. Select an available release.');return;}this.aboutError.set('');if(updateUrl)history.pushState({},'',`/about?version=${encodeURIComponent(version)}`);try{const response=await fetch('/assets/changelog/'+encodeURIComponent(entry.markdown));if(!response.ok)throw new Error('Release notes unavailable');const markdown=await response.text(),parts=markdown.split(/^## (.+)$/m),groups=[];for(let i=1;i<parts.length;i+=2)groups.push({title:parts[i],items:parts[i+1].trim().split('\n').filter(Boolean).map(line=>line.replace(/^- /,''))});this.noteGroups.set(groups);}catch(error){this.notify(error);this.aboutError.set('Release notes unavailable');}}
  openAbout(){this.about.set(true);void this.selectVersion(this.currentVersion());}
  closeAbout(){this.about.set(false);history.pushState({},'','/');}
  @HostListener('window:popstate') route(){this.about.set(location.pathname==='/about');if(this.about())void this.selectVersion(new URLSearchParams(location.search).get('version')??this.currentVersion(),false);}
  async serverRequest(path:string,method='GET',body?:unknown){const response=await fetch('/api/'+path,{method,headers:{Authorization:'Bearer '+this.apiToken(),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error(response.status===401?'Enter the local API token from your environment file.':`Server request failed (${response.status}).`);return response.json();}
  async refreshProjects(){try{this.projects.set(await this.serverRequest('projects'));this.editor.status.set('Connected to local document service');}catch(error){this.notify(error);}}
  async saveServer(){try{await this.serverRequest('projects','POST',this.editor.document());await this.refreshProjects();this.editor.status.set('Project saved to local server');}catch(error){this.notify(error);}}
  async openServer(id:string){try{const doc=await this.serverRequest('projects/'+encodeURIComponent(id));this.editor.open(JSON.stringify(doc));this.dialog.set(false);this.fit();}catch(error){this.notify(error);}}
  async spatialPreview(){this.spatial.set(true);try{const {createSpatialPreview}=await import('./spatial');requestAnimationFrame(async()=>{try{if(this.spatialHost){const dispose=await createSpatialPreview(this.spatialHost.nativeElement,this.editor.document(),this.editor.renderer);if(this.spatial())this.disposeSpatial=dispose;else dispose();}}catch(error){this.notify(error);this.closeSpatial();}});}catch(error){this.notify(error);this.closeSpatial();}}
  closeSpatial(){this.disposeSpatial?.();this.disposeSpatial=undefined;this.spatial.set(false);}
}
