"""Owner and contribution metadata policy tests."""
import json
from pathlib import Path
import unittest
from harness.check_contribution import check_text,check_metadata

class ContributionTests(unittest.TestCase):
    def setUp(self):
        self.policy=json.loads(Path("harness/contribution-policy.json").read_text())
        self.report={"headSha":"abc","commits":[{"authorLogin":"Yoshikemolo","committerLogin":"Yoshikemolo","message":"docs: define the studio architecture"}],"pullRequest":{"authorLogin":"Yoshikemolo","title":"docs: define the studio architecture","body":"Define requirements, contracts and acceptance scenarios."}}
    def test_valid(self):
        self.assertEqual([],check_metadata(self.report,"abc",self.policy))
    def test_wrong_identity(self):
        self.report["commits"][0]["committerLogin"]="automation"
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_forbidden_text(self):
        for text in ["docs: update ChatGPT guidance","docs: update\n\nCo-authored-by: Helper <x@example.invalid>","docs: update \U0001f680","docs: actualiza documentación","Update documentation","docs: generated by helper","docs: add GPT-5 references"]:
            with self.subTest(text=text):
                self.assertTrue(check_text(text,"Commit",self.policy))
    def test_stale_and_missing_metadata(self):
        self.assertTrue(check_metadata(self.report,"def",self.policy))
        self.assertTrue(check_metadata({"headSha":"abc","commits":[]},"abc",self.policy))
    def test_pr_identity(self):
        self.report["pullRequest"]["authorLogin"]="someone-else"
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_conventional_scopes(self):
        self.assertEqual([],check_text("feat(renderer)!: change the transform contract","Commit",self.policy))
    def test_legacy_exemption_is_exact(self):
        legacy={"sha":"310daca1c44d942b10a882552dbe8f5166a0ec78","authorLogin":"Yoshikemolo","committerLogin":"web-flow","message":"Merge pull request #2 from Yoshikemolo/feat/FEAT-0023-quality-evidence"}
        self.report["commits"].append(legacy)
        self.assertEqual([],check_metadata(self.report,"abc",self.policy))
        legacy["sha"]="0"*40
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
        del legacy["sha"]
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_malformed_exemption_fails_closed(self):
        for entry in ({"sha":"310daca","reason":"short"},{"sha":"a"*40,"reason":" "},"a"*40):
            with self.subTest(entry=entry):
                with self.assertRaises(ValueError):
                    check_metadata(self.report,"abc",{**self.policy,"legacyCommitExemptions":[entry]})
    def test_verified_web_merge_with_conventional_title_passes(self):
        merge={"sha":"b"*40,"authorLogin":"Yoshikemolo","committerLogin":"web-flow","verified":True,"message":"feat(editor): add the drawing preview (#17)"}
        self.report["commits"].append(merge)
        self.assertEqual([],check_metadata(self.report,"abc",self.policy))
    def test_web_merge_requires_verification_owner_and_conventional_text(self):
        base={"sha":"b"*40,"authorLogin":"Yoshikemolo","committerLogin":"web-flow","verified":True,"message":"feat(editor): add the drawing preview"}
        for change in ({"verified":False},{"verified":"true"},{"authorLogin":"someone-else"},{"committerLogin":"someone-else"},{"message":"Merge pull request #17 from Yoshikemolo/feat/x"}):
            with self.subTest(change=change):
                report={**self.report,"commits":[{k:v for k,v in {**base,**change}.items()}]}
                self.assertTrue(check_metadata(report,"abc",self.policy))
        report={**self.report,"commits":[{k:v for k,v in base.items() if k!="verified"}]}
        self.assertTrue(check_metadata(report,"abc",self.policy))
