"""Owner and contribution metadata policy tests."""
import json
from pathlib import Path
import unittest
from harness.check_contribution import check_text,check_metadata

class ContributionTests(unittest.TestCase):
    def setUp(self):
        self.policy=json.loads(Path("harness/contribution-policy.json").read_text())
        self.report={"headSha":"abc","commits":[{"authorLogin":"Yoshikemolo","committerLogin":"Yoshikemolo","message":"docs: define the studio architecture"}],"pullRequest":{"authorLogin":"Yoshikemolo","title":"docs: define the studio architecture","body":"Define requirements, contracts and acceptance scenarios."}}
    def test_valid(self):
        self.assertEqual([],check_metadata(self.report,"abc",self.policy))
    def test_wrong_identity(self):
        self.report["commits"][0]["committerLogin"]="automation"
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_forbidden_text(self):
        for text in ["docs: update ChatGPT guidance","docs: update\n\nCo-authored-by: Helper <x@example.invalid>","docs: update \U0001f680","docs: actualiza documentación","Update documentation","docs: generated by helper","docs: add GPT-5 references"]:
            with self.subTest(text=text):
                self.assertTrue(check_text(text,"Commit",self.policy))
    def test_stale_and_missing_metadata(self):
        self.assertTrue(check_metadata(self.report,"def",self.policy))
        self.assertTrue(check_metadata({"headSha":"abc","commits":[]},"abc",self.policy))
    def test_pr_identity(self):
        self.report["pullRequest"]["authorLogin"]="someone-else"
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_conventional_scopes(self):
        self.assertEqual([],check_text("feat(renderer)!: change the transform contract","Commit",self.policy))
    def test_legacy_exemption_is_exact(self):
        legacy={"sha":"310daca1c44d942b10a882552dbe8f5166a0ec78","authorLogin":"Yoshikemolo","committerLogin":"web-flow","message":"Merge pull request #2 from Yoshikemolo/feat/FEAT-0023-quality-evidence"}
        self.report["commits"].append(legacy)
        self.assertEqual([],check_metadata(self.report,"abc",self.policy))
        legacy["sha"]="0"*40
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
        del legacy["sha"]
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_malformed_exemption_fails_closed(self):
        for entry in ({"sha":"310daca","reason":"short"},{"sha":"a"*40,"reason":" "},"a"*40):
            with self.subTest(entry=entry):
                with self.assertRaises(ValueError):
                    check_metadata(self.report,"abc",{**self.policy,"legacyCommitExemptions":[entry]})

    def test_diagnostics_identify_each_historical_merge_without_exempting_it(self):
        commits = [
            {"sha": "7c2af886570ded96107934cd2822f4665e3448e4", "authorLogin": "Yoshikemolo", "committerLogin": "web-flow", "message": "Merge pull request #5"},
            {"sha": "aa92505cd29dedcb6d13e414db875679543e390e", "authorLogin": "Yoshikemolo", "committerLogin": "web-flow", "message": "Merge pull request #9"},
        ]
        errors = check_metadata({**self.report, "commits": commits}, "abc", self.policy)
        self.assertEqual(4, len(errors))
        for commit in commits:
            self.assertEqual(2, sum(commit["sha"] in error for error in errors))
        self.assertTrue(any("web-flow" in error for error in errors))

    def test_proposed_text_preflight_and_metadata_are_both_enforced(self):
        from contextlib import redirect_stdout
        from io import StringIO
        from tempfile import TemporaryDirectory
        from unittest.mock import patch
        from harness.check_contribution import main
        with TemporaryDirectory() as directory:
            folder = Path(directory)
            message, title, body, report = [folder/name for name in ("message", "title", "body", "report")]
            message.write_text("fix(ci): check contribution before publication", encoding="utf-8")
            title.write_text("fix(ci): check contribution before publication", encoding="utf-8")
            body.write_text("Validate proposed text before publication.", encoding="utf-8")
            command = ["check", "--message-file", str(message), "--pr-title-file", str(title), "--pr-body-file", str(body)]
            with patch("sys.argv", command), redirect_stdout(StringIO()):
                self.assertEqual(0, main())
            title.write_text("Dev", encoding="utf-8")
            with patch("sys.argv", command), redirect_stdout(StringIO()):
                self.assertEqual(1, main())
            title.write_text("fix(ci): valid title", encoding="utf-8")
            bad = {**self.report, "headSha": "different"}
            report.write_text(json.dumps(bad), encoding="utf-8")
            with patch("sys.argv", command+[str(report), "--head", "abc"]), redirect_stdout(StringIO()):
                self.assertEqual(1, main())
