"""Owner and contribution metadata policy tests."""
import json
from pathlib import Path
import unittest
from harness.check_contribution import check_text,check_metadata

class ContributionTests(unittest.TestCase):
    def setUp(self):
        self.policy=json.loads(Path("harness/contribution-policy.json").read_text())
        self.report={"headSha":"abc","commits":[{"authorLogin":"Yoshikemolo","committerLogin":"Yoshikemolo","message":"docs: define the studio architecture"}],"pullRequest":{"authorLogin":"Yoshikemolo","title":"docs: define the studio architecture","body":"Define requirements, contracts and acceptance scenarios."}}
    def test_valid(self):
        self.assertEqual([],check_metadata(self.report,"abc",self.policy))
    def test_wrong_identity(self):
        self.report["commits"][0]["committerLogin"]="automation"
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_forbidden_text(self):
        for text in ["docs: update ChatGPT guidance","docs: update\n\nCo-authored-by: Helper <x@example.invalid>","docs: update \U0001f680","docs: actualiza documentación","Update documentation","docs: generated by helper","docs: add GPT-5 references"]:
            with self.subTest(text=text):
                self.assertTrue(check_text(text,"Commit",self.policy))
    def test_stale_and_missing_metadata(self):
        self.assertTrue(check_metadata(self.report,"def",self.policy))
        self.assertTrue(check_metadata({"headSha":"abc","commits":[]},"abc",self.policy))
    def test_pr_identity(self):
        self.report["pullRequest"]["authorLogin"]="someone-else"
        self.assertTrue(check_metadata(self.report,"abc",self.policy))
    def test_conventional_scopes(self):
        self.assertEqual([],check_text("feat(renderer)!: change the transform contract","Commit",self.policy))
