// @vitest-environment happy-dom
import '@angular/compiler';
import { beforeEach,describe,it,expect,vi } from 'vitest';
import { createCanvas,loadImage } from '@napi-rs/canvas';
import { EditorService } from '../src/app/editor.service';
describe('editor command facade',()=>{
 beforeEach(()=>localStorage.clear());
 it('draws and moves an editable shape, with undo and redo',()=>{const e=new EditorService();e.tool.set('rectangle');e.start({x:10,y:20});e.move({x:110,y:100});e.end();expect(e.selected()?.width).toBe(100);e.tool.set('select');e.start({x:30,y:30});e.move({x:50,y:50});e.end();expect(e.selected()?.x).toBe(30);e.undo();expect(e.selected()?.x).toBe(10);e.redo();expect(e.selected()?.x).toBe(30);});
 it('cancels incomplete drawing and protects locked layers',()=>{const e=new EditorService();e.tool.set('ellipse');e.start({x:0,y:0});e.move({x:100,y:100});e.cancel();expect(e.document().layers).toHaveLength(0);e.start({x:0,y:0});e.move({x:100,y:100});e.end();const id=e.selected()!.id;e.toggle(id,'locked');e.updateLayer({width:500});e.remove();expect(e.document().layers).toHaveLength(1);expect(e.selected()?.width).toBe(100);});
 it('duplicates, reorders and round trips native document data',()=>{const e=new EditorService();e.tool.set('text');e.start({x:10,y:10});e.end();e.updateLayer({text:'Hello'});e.duplicate();expect(e.document().layers).toHaveLength(2);const id=e.selectedId();e.moveOrder(-1);expect(e.document().layers[0].id).toBe(id);const saved=JSON.stringify(e.document());e.reset();e.open(saved);expect(e.document().layers[0].text).toBe('Hello');e.selectedId.set(id);e.remove();expect(e.document().layers).toHaveLength(1);});
 it('paints pixels and erases them while keeping undo evidence',async()=>{const canvases=new WeakMap<HTMLCanvasElement,ReturnType<typeof createCanvas>>();const native=(element:HTMLCanvasElement)=>{let canvas=canvases.get(element);if(!canvas){canvas=createCanvas(element.width,element.height);canvases.set(element,canvas);}return canvas;};const context=vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockImplementation(function(this:HTMLCanvasElement){return native(this).getContext('2d') as never;});const encode=vi.spyOn(HTMLCanvasElement.prototype,'toDataURL').mockImplementation(function(this:HTMLCanvasElement){return native(this).toDataURL('image/png');});try{const e=new EditorService();e.tool.set('brush');e.fill.set('#ff0000');e.size.set(20);e.start({x:50,y:50});e.move({x:80,y:50});e.end();const source=e.selected()!.source,image=await loadImage(source);const pixelCanvas=createCanvas(1200,800);pixelCanvas.getContext('2d').drawImage(image,0,0);expect([...pixelCanvas.getContext('2d').getImageData(65,50,1,1).data]).toEqual([255,0,0,255]);vi.spyOn(e.renderer,'image').mockReturnValue(image as unknown as HTMLImageElement);e.tool.set('eraser');e.start({x:65,y:50});e.end();const erased=await loadImage(e.selected()!.source);pixelCanvas.getContext('2d').clearRect(0,0,1200,800);pixelCanvas.getContext('2d').drawImage(erased,0,0);expect(pixelCanvas.getContext('2d').getImageData(65,50,1,1).data[3]).toBe(0);e.undo();expect(e.selected()!.source).toBe(source);}finally{context.mockRestore();encode.mockRestore();}});
});
