// @vitest-environment happy-dom
import '@angular/compiler';
import {beforeEach,describe,it,expect} from 'vitest';
import {EditorService} from '../src/app/editor.service';
import {newLayer} from '../../../packages/domain/src/document';
import {anchor,worldPoint} from '../../../packages/domain/src/curves';
beforeEach(()=>localStorage.clear());
describe('numeric selection transformations',()=>{
 it('moves a complete group atomically and undo restores it',()=>{const e=new EditorService();e.document.update(d=>({...d,layers:[{...newLayer('rectangle','a',{x:10,y:20}),groupPath:['g']},{...newLayer('rectangle','b',{x:110,y:20}),groupPath:['g']}]}));e.selectLayer('a');const before=structuredClone(e.document());expect(e.displaceSelection(20,-10)).toBe(true);expect(e.document().layers.map(l=>l.x)).toEqual([30,130]);e.undo();expect(e.document()).toEqual(before);});
 it('rotates around the requested reference point',()=>{const e=new EditorService();const l={...newLayer('rectangle','a',{x:10,y:0}),width:20,height:20};e.document.update(d=>({...d,layers:[l]}));e.selectLayer('a');e.rotateSelection(90,{x:0,y:0});expect(e.selected()!.x).toBeCloseTo(-20);expect(e.selected()!.y).toBeCloseTo(10);expect(e.selected()!.rotation).toBe(90);});
 it('moves selected vertices and both controls in world coordinates without moving other anchors',()=>{const e=new EditorService();const l={...newLayer('path','a',{x:10,y:20}),width:100,height:100,rotation:30,curves:[{closed:false,nodes:[{...anchor({x:0,y:0}),outgoing:{x:20,y:0}},anchor({x:100,y:100})]}]};e.document.update(d=>({...d,layers:[l]}));e.selectLayer('a');e.activeNodes.set(['0:0']);const p=worldPoint(l,l.curves[0].nodes[0].point),control=worldPoint(l,l.curves[0].nodes[0].outgoing),fixed=worldPoint(l,l.curves[0].nodes[1].point);e.displaceSelection(15,7);const next=e.selected()!;expect(worldPoint(next,next.curves![0].nodes[0].point).x).toBeCloseTo(p.x+15);expect(worldPoint(next,next.curves![0].nodes[0].outgoing).y).toBeCloseTo(control.y+7);expect(worldPoint(next,next.curves![0].nodes[1].point).x).toBeCloseTo(fixed.x);});
 it('rejects transformations outside native document bounds before touching history',()=>{const e=new EditorService();e.document.update(d=>({...d,layers:[newLayer('rectangle','a',{x:10,y:20})]}));e.selectLayer('a');const before=structuredClone(e.document());expect(e.displaceSelection(1e6,0)).toBe(false);expect(e.rotateSelection(90,{x:1e12,y:1e12})).toBe(false);expect(e.document()).toEqual(before);e.undo();expect(e.document()).toEqual(before);});
 it('duplicates do not retain links to a formerly grouped original',()=>{const e=new EditorService();e.document.update(d=>({...d,layers:[{...newLayer('rectangle','a',{x:10,y:20}),regroupPath:['g']},{...newLayer('rectangle','b',{x:100,y:20}),regroupPath:['g']}]}));e.selectLayer('a');e.duplicate();expect(e.selected()?.regroupPath).toBeUndefined();});
 it('rejects locked selections and nonfinite inputs',()=>{const e=new EditorService();const l={...newLayer('rectangle','a',{x:10,y:20}),locked:true};e.document.update(d=>({...d,layers:[l]}));e.selectedId.set('a');expect(e.displaceSelection(20,10)).toBe(false);expect(e.rotateSelection(NaN)).toBe(false);expect(e.selected()).toEqual(l);});
});
