// @vitest-environment happy-dom
import '@angular/compiler';
import {beforeEach,describe,it,expect} from 'vitest';
import {EditorService} from '../src/app/editor.service';
import {parseDocument} from '../../../packages/domain/src/document';
import {worldPoint} from '../../../packages/domain/src/curves';
beforeEach(()=>localStorage.clear());
function setup(){const e=new EditorService();e.updateProceduralDefaults('wall',{thickness:20});expect(e.createProcedural('wall',{x:100,y:100},{x:500,y:100})).toBe(true);return e;}
describe('procedural architecture editing',()=>{
 it('creates a wall by dragging and commits one reversible layer',()=>{const e=new EditorService();e.setTool('wall');e.start({x:50,y:50});e.move({x:350,y:50});e.end();expect(e.selected()?.procedural?.type).toBe('wall');expect(parseDocument(JSON.stringify(e.document())).layers).toHaveLength(1);e.undo();expect(e.document().layers).toHaveLength(0);});
 it('cancels a procedural drawing and restores selection',()=>{const e=setup(),before=structuredClone(e.document()),id=e.selectedId();e.setTool('pillar');e.start({x:300,y:200});e.move({x:340,y:240});e.cancel();expect(e.document()).toEqual(before);expect(e.selectedId()).toBe(id);});
 it('creates hosted openings and follows host movement; deleting the wall detaches in place',()=>{const e=setup(),wall=e.selectedId()!;expect(e.createProcedural('door',{x:300,y:100})).toBe(true);const door=e.selectedId()!,opening=e.selected()!;expect(opening.procedural).toMatchObject({type:'door',host:{wallId:wall}});e.selectLayer(wall);e.displaceSelection(30,40);const moved=e.document().layers.find(l=>l.id===door)!;expect(moved.x).toBeCloseTo(opening.x+30);expect(moved.y).toBeCloseTo(opening.y+40);e.remove();const detached=e.document().layers.find(l=>l.id===door)!;expect(detached.procedural).not.toHaveProperty('host');expect(detached.x).toBeCloseTo(moved.x);expect(detached.y).toBeCloseTo(moved.y);});
 it('moving an opening alone detaches and retains the requested displacement',()=>{const e=setup();e.createProcedural('window',{x:300,y:100});const original=e.selected()!;expect(e.displaceSelection(20,50)).toBe(true);expect(e.selected()?.procedural).not.toHaveProperty('host');expect(e.selected()!.x).toBeCloseTo(original.x+20);expect(e.selected()!.y).toBeCloseTo(original.y+50);});
 it('updates parameters without changing identity and rescales individual leaves proportionally',()=>{const e=setup();e.createProcedural('door',{x:300,y:100});const id=e.selectedId();expect(e.updateProcedural({width:120,leafWidths:[40,80]})).toBe(true);expect(e.updateProcedural({width:180})).toBe(true);expect(e.selected()?.procedural).toMatchObject({width:180,leafWidths:[60,120]});expect(e.selectedId()).toBe(id);const before=structuredClone(e.document());expect(e.updateProcedural({width:-1})).toBe(false);expect(e.document()).toEqual(before);});
 it('creates circular pillars with equal dimensions and rejects unsupported conversions',()=>{const e=new EditorService();e.updateProceduralDefaults('pillar',{shape:'circle',width:30});e.createProcedural('pillar',{x:100,y:100},{x:140,y:160});expect(e.selected()?.procedural).toMatchObject({shape:'circle',width:40,depth:40});const before=structuredClone(e.document());e.defineSymbol();e.pathAction('smooth');expect(e.document()).toEqual(before);});
 it('resizes procedural metadata with selection transforms and keeps free insertion stable when changing swing',()=>{
  const e=new EditorService();e.createProcedural('door',{x:200,y:200});const jambCenter=()=>{const l=e.selected()!,nodes=[...l.curves![0].nodes,...l.curves![1].nodes].map(n=>worldPoint(l,n.point));return {x:nodes.reduce((sum,p)=>sum+p.x,0)/nodes.length,y:nodes.reduce((sum,p)=>sum+p.y,0)/nodes.length};};
  const before=jambCenter();expect(e.updateProcedural({openingAngle:35})).toBe(true);expect(jambCenter().x).toBeCloseTo(before.x);expect(jambCenter().y).toBeCloseTo(before.y);const width=(e.selected()!.procedural as {width:number}).width;e.transformBy(0,2);expect((e.selected()!.procedural as {width:number}).width).toBeCloseTo(width*2);
 });
 it('duplicates openings without attaching the copy to the original wall',()=>{const e=setup();e.createProcedural('door',{x:300,y:100});const original=e.selected()!;e.duplicate();expect(e.selected()?.procedural).not.toHaveProperty('host');expect(e.selected()!.x).toBeCloseTo(original.x+20);});
 it('retains centerline measurements after normalized wall generation',()=>{const e=setup(),l=e.selected()!,p=l.procedural!;if(p.type!=='wall')throw Error();expect(worldPoint(l,p.start)).toEqual({x:100,y:100});expect(worldPoint(l,p.end)).toEqual({x:500,y:100});});
});
