sonar.projectKey=ximply-design-studio-api
sonar.sources=services/api/src
sonar.tests=services/api/tests
sonar.python.coverage.reportPaths=reports/api/coverage.xml
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
