sonar.projectKey=ximply-design-studio-persistence
sonar.sources=services/persistence/src
sonar.tests=services/persistence/tests
sonar.javascript.lcov.reportPaths=reports/persistence/lcov.info
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
