sonar.projectKey=ximply-design-studio-web
sonar.sources=apps/web/src
sonar.tests=apps/web/tests
sonar.javascript.lcov.reportPaths=reports/web/lcov.info
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
