import { describe,it,expect } from 'vitest';
import { blankDocument,newLayer,parseDocument,resizeLayer,svgExport,hitTest,Layer } from '../src/document';
import { defaultDimensionFormat,dimensionGeometry,validDimension } from '../src/dimensions';
import { lineEndGeometry,validLineEnds } from '../src/line-endings';
function fixture():Layer{return {...newLayer('path','dimension',{x:10,y:20},'#112233','#112233',1),width:96,height:40,fontSize:12,dimension:{kind:'linear',anchors:[{x:0,y:0},{x:96,y:0}],labelPosition:{x:48,y:30},text:'',format:{...defaultDimensionFormat,unit:'in'},extension:{stroke:'#112233',strokeWidth:1,gap:2,overshoot:4}}};}
describe('dimension geometry and contracts',()=>{
 it('measures world geometry and formats physical units independently of display zoom',()=>{const l=fixture(),g=dimensionGeometry(l);expect(g.value).toBe(1);expect(g.text).toBe('1.00 in');expect(g.lines.at(-1)).toEqual({a:{x:10,y:50},b:{x:106,y:50},extension:false});expect(dimensionGeometry(resizeLayer(l,192,80)).text).toBe('2.00 in');expect(dimensionGeometry({...l,rotation:90}).value).toBeCloseTo(1);});
 it('measures signed-side angular arcs without stretching text or marker sizes',()=>{const l=fixture();l.dimension!.kind='angular';l.dimension!.anchors=[{x:50,y:0},{x:0,y:0},{x:0,y:50}];const g=dimensionGeometry(l);expect(g.text).toBe('90.00°');expect(g.arc!.endAngle-g.arc!.startAngle).toBeCloseTo(Math.PI/2);const resized=resizeLayer(l,192,80);expect(resized.fontSize).toBe(12);expect(dimensionGeometry(resized).ends[0].style.size).toBe(10);});
 it('roundtrips metadata and rejects invalid bounded nested contracts and old versions',()=>{const l=fixture(),doc={...blankDocument(),layers:[l]};expect(parseDocument(JSON.stringify(doc))).toEqual(doc);expect(()=>parseDocument(JSON.stringify({...doc,version:1}))).toThrow();for(const decimals of [-1,9,0.5,Infinity])expect(validDimension({...l.dimension,format:{...l.dimension!.format,decimals}})).toBe(false);expect(validLineEnds({linked:true,start:{kind:'cross',placement:'tip',size:10},end:{kind:'dot',placement:'base',size:0}})).toBe(false);});
 it('supports label override escaping and world-space label hit testing',()=>{const l=fixture();l.dimension!.text='<custom>';const svg=svgExport({...blankDocument(),layers:[l]});expect(svg).toContain('&lt;');expect(svg).not.toContain('<custom>');expect(hitTest(l,{x:58,y:50})).toBe(true);expect(hitTest(l,{x:58,y:150})).toBe(false);});
 it('places tip at endpoint or extends outward from the base',()=>{const p={x:10,y:0},u={x:1,y:0};const tip=lineEndGeometry(p,u,{kind:'triangle',placement:'tip',size:10});expect(tip.points[1]).toEqual(p);const base=lineEndGeometry(p,u,{kind:'triangle',placement:'base',size:10});expect(base.points[1]).toEqual({x:20,y:0});expect(base.points[0].x).toBe(10);});
});
