import { describe,it,expect } from 'vitest';
import { blankDocument,bounds,DocumentHistory,hitTest,localPoint,newLayer,normalizePath,parseDocument,pick,resizeLayer,resizeFromCorner,svgExport } from '../src/document';
describe('editable document commands',()=>{
 it('resizes all corners and preserves the opposite anchor of a rotated layer',()=>{const layer={...newLayer('rectangle','a',{x:0,y:0}),width:100,height:100};for(const [corner,x,y] of [['tl',-50,-50],['tr',150,-50],['bl',-50,150],['br',150,150]] as const){const result=resizeFromCorner(layer,{x,y},corner);expect(result.width).toBe(150);expect(result.height).toBe(150);}const rotated=resizeFromCorner({...layer,rotation:90},{x:-100,y:200},'br');expect(rotated.x).toBeCloseTo(-100);expect(rotated.y).toBeCloseTo(0);expect(rotated.width).toBeCloseTo(200);expect(rotated.height).toBeCloseTo(200);});
 it('normalizes drawing direction and minimum size',()=>{expect(bounds({x:20,y:30},{x:5,y:10})).toEqual({x:5,y:10,width:15,height:20});expect(bounds({x:0,y:0},{x:0,y:0}).width).toBe(1);});
 it('selects topmost visible unlocked shape with rotation',()=>{const bottom={...newLayer('rectangle','a',{x:0,y:0}),width:100,height:100},top={...bottom,id:'b'};expect(pick([bottom,top],{x:50,y:50})?.id).toBe('b');top.locked=true;expect(pick([bottom,top],{x:50,y:50})?.id).toBe('a');bottom.visible=false;expect(pick([bottom,top],{x:50,y:50})).toBeUndefined();expect(localPoint({...top,rotation:90},{x:50,y:0}).x).toBeCloseTo(0);});
 it('uses ellipse and segment geometry rather than only bounding boxes',()=>{const ellipse={...newLayer('ellipse','a',{x:0,y:0}),width:100,height:100};expect(hitTest(ellipse,{x:50,y:50})).toBe(true);expect(hitTest(ellipse,{x:-20,y:-20})).toBe(false);const path=normalizePath(newLayer('path','p',{x:0,y:0}),[{x:10,y:10},{x:110,y:110}]);expect(hitTest(path,{x:50,y:50})).toBe(true);expect(hitTest(path,{x:100,y:10})).toBe(false);expect(resizeLayer(path,200,200).points[1]).toEqual({x:200,y:200});});
 it('preserves before states through undo redo and bounded history',()=>{const history=new DocumentHistory(2),doc=blankDocument();expect(history.undo(doc)).toBe(doc);expect(history.redo(doc)).toBe(doc);history.commit(doc);doc.name='Changed';const previous=history.undo(doc);expect(previous.name).not.toBe(doc.name);expect(history.canRedo).toBe(true);expect(history.redo(previous).name).toBe('Changed');history.commit(doc);history.commit(doc);history.commit(doc);history.undo(doc);history.undo(doc);expect(history.canUndo).toBe(false);history.clear();expect(history.canRedo).toBe(false);});
 it('round trips every layer kind and rejects invalid identity or format',()=>{const doc=blankDocument();doc.layers=['rectangle','ellipse','path','text','image'].map((kind,i)=>newLayer(kind as 'rectangle','id'+i,{x:0,y:0}));expect(parseDocument(JSON.stringify(doc))).toEqual(doc);expect(()=>parseDocument('{}')).toThrow();doc.layers.push(doc.layers[0]);expect(()=>parseDocument(JSON.stringify(doc))).toThrow();});
 it('rejects invalid styles transforms external images and unbounded content',()=>{const baseline=blankDocument();baseline.layers=[newLayer('image','x',{x:0,y:0})];for(const patch of [{kind:'script'},{blend:'evil'},{width:0},{opacity:2},{fill:'red'},{x:Infinity},{source:'https://remote/image.png'},{points:[{x:'bad',y:0}]},{adjustments:{brightness:999,contrast:100,saturation:100,blur:0}},{text:5}]){const doc=structuredClone(baseline);Object.assign(doc.layers[0],patch);expect(()=>parseDocument(JSON.stringify(doc))).toThrow();}expect(()=>parseDocument(JSON.stringify({...baseline,width:9000}))).toThrow();});
 it('exports editable vector primitives and escapes text',()=>{const doc=blankDocument();doc.layers=['rectangle','ellipse','path','text','image'].map((kind,i)=>({...newLayer(kind as 'rectangle','id'+i,{x:5,y:8}),text:'<script>&"\'',source:'data:image/png;base64,AAAA',points:[{x:0,y:0},{x:5,y:5}]}));const svg=svgExport(doc);for(const tag of ['rect','ellipse','polyline','text','image'])expect(svg).toContain('<'+tag);expect(svg).toContain('&lt;script&gt;&amp;&quot;&apos;');expect(svg).not.toContain('<script>');doc.layers[0].visible=false;expect(svgExport(doc)).not.toContain('transform="translate(5 8) rotate(0 0.5 0.5)" opacity="1" style="mix-blend-mode:normal"><rect');});
});
